export const ADD_RECIPE = "ADD_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const SAVE_EDITED_RECIPE = "SAVE_EDITED_RECIPE";
export const SET_RETRIEVED_STATE = "SET_RETRIEVED_STATE";
export const REMOVE_RECIPE = "REMOVE_RECIPE";
export const SAVE_RECIPES = "SAVE_RECIPES";